services:
  - type: web
    name: weathersense-backend
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    plan: free
    autoDeploy: true
    branch: main
    buildCommand: ""
    envVars:
      - key: PORT
        value: 10000
